[package]
name = "strobe-rs"
description = "An implementation of the Strobe protocol framework in pure Rust"
version = "0.3.0"
authors = ["Michael Rosenberg <micro@fastmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["crypto", "cryptography", "strobe", "protocol", "framework"]

[dependencies]
bitflags = "1.0"
byteorder = "1.2"
lazy_static = "1.0"
subtle = "0.6"
tiny-keccak = "1.0"
