[package]
name = "strobe-rs"
version = "0.1.0"
authors = ["Michael Rosenberg <micro@fastmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["crypto", "cryptography", "strobe", "protocol", "framework", "pure"]

[dependencies]
bitflags = "1.0"
byteorder = "1.2"
lazy_static = "1.0"
tiny-keccak = "1.0"
